apiVersion: v1
kind: Pod
metadata:
  name: setup
spec:
  containers:
  - image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/dbsetup:1.0
    name: setupdb
    restartPolicy: Never
    ports:
    - containerPort: 3000
    envFrom:
    - configMapRef:
      name: walletmap


# docker tag dbsetup:1.0 default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/dbsetup:1.0

# docker push default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/dbsetup:1.0

# kubectl apply -f webserver.yaml

 