apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgrespvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

