apiVersion: v1
data:
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: "2022-01-25T12:50:00Z"
  name: dbsecret
  namespace: labproj23
  resourceVersion: "79618652"
  uid: 889181c6-9003-48f0-bc3a-7c1afdf22b7c
type: Opaque

# kubectl create secret generic dbsecret --from-literal=POSTGRES_PASSWORD=admin --from-literal=POSTGRES_USER=postgres -o yaml