apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: projekt
  name: deploy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallet-db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wallet-db
    spec:
      containers:
      - command:
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/postgres-wallet:1.0
        name: wallet-db
        resources: {}
        ports:
        - containerPort: 5432
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: UNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PASSWD
        volumeMounts:
        - mountPath: /data
          name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: postgres-pvc
status: {}
