apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-db
  name: deploy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-db
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-db
    spec:
      containers:
      - name: deploy-db
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/postgres-wallet:1.0
        resources: {}
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-cfm
        volumeMounts:
        - mountPath: /data
          name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: postgres-pvc
status: {}