apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-db
  name: deploy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-db
  strategy: {}
  template:
    metadata:
      labels:
        app: deploy-db
    spec:
      containers:
      - name: deploy-db
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/postgres-wallet:1.0
        resources: {}
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-cfm
        env:
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: USER_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PASSWORD_DB
        volumeMounts:
        - mountPath: /data
          name: db-volume
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: postgres-pvc
status: {}


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   labels:
#     app: db-deploy
#   name: db-deploy
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: db-deploy
#   strategy: {}
#   template:
#     metadata:
#       labels:
#         app: db-deploy
#     spec:
#       containers:
#       - name: db-deploy
#         image: image-registry.openshift-image-registry.svc:5000/labproj22/postgres:14.1
#         resources: {}
#         ports:
#         - containerPort: 5432
#         envFrom:
#         - configMapRef:
#             name: db-cmap
#         env:
#         - name: USER_DB
#           valueFrom:
#             secretKeyRef:
#               name: db-secret
#               key: USER_DB
#         - name: POSTGRES_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: db-secret
#               key: PASSWORD_DB
#         volumeMounts:
#         - mountPath: /data
#           name: postgredb
#       volumes:
#       - name: postgredb
#         persistentVolumeClaim:
#           claimName: db-pvc
# status: {}