
#### CONFIG_MAP ###

apiVersion: v1
data:
  POSTGRES_DB: MonthWallet
kind: ConfigMap
metadata:
  name: dbcm
  namespace: labproj23

---

#### SECRET ###

apiVersion: v1
data:
  POSTGRES_PASSWORD: YWRtaW4=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  name: dbsecret
  namespace: labproj23
type: Opaque

---

#### PVC ###

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbpvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

---

#### DEPLOYMENT ###

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dbdeployment
  name: dbdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbdeployment
  strategy: {}
  template:
    metadata:
      labels:
        app: dbdeployment
    spec:
      containers:
      - name: dbdeployment
        image: image-registry.openshift-image-registry.svc:5000/labproj23/postgres-wallet:1.0
        resources: {}
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: dbcm
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbsecret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: /data
          name: dbvolume
      volumes:
      - name: dbvolume
        persistentVolumeClaim:
          claimName: dbpvc
status: {}

---

#### SERVICE ###

apiVersion: v1
kind: Service
metadata:
  name: dbsvc
  labels:
    app: dbdeployment
spec:
  ports:
  - port: 5432
  selector:
    app: dbdeployment
  type: NodePort
