apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

