
---

#### CONFIGMAP ###

apiVersion: v1
kind: ConfigMap
metadata:
  name: walletmap
data:
  DATABASE_URL: postgresql://postgres@db-svc.labproj23.svc.cluster.local:5432/MonthWallet
 
---

#### DEPLOYMENT ###

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: projektapp
  name: projektapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projektapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: projektapp
    spec:
      containers:
      - command:
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/walletapp:1.0
        name: projektapp
        resources: {}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: walletmap      
status: {}

---

#### SERVICE ###

apiVersion: v1
kind: Service
metadata:
  name: projektappsvc
  labels:
    app: projektapp
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: projektapp
  type: ClusterIP

---

#### ROUTE ###


apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: projektapp
  name: apprte
spec:
  host: ""
  port:
    targetPort: 3000
  to:
    kind: Service
    name: projektappsvc
    weight: 100