apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: projektapp
  name: projektapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projektapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: projektapp
    spec:
      containers:
      - command:
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/walletapp:1.0
        name: projektapp
        resources: {}
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: walletmap

      #   volumeMounts:
      #   - mountPath: /app/files
      #     name: ex1-volume
      # volumes:
      # - name: ex1-volume
      #   persistentVolumeClaim:
      #     claimName: ex1-pvc
      
status: {}