# DATABASE_URL = ""
# DATABASE_URL=postgresql://postgres:admin@localhost:5433/MonthWallet
# STAT_SERVICE_URL = localhost:3001/api/stats


apiVersion: v1
kind: ConfigMap
metadata:
  name: walletmap
data:
  PORT: 8081
  DATABASE_URL: postgresql://postgres:admin@localhost:5433/MonthWallet
