apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: projektapp
  name: projekt
spec:
  host: ""
  port:
    targetPort: 8080
  to:
    kind: Service
    name: projektappsvc
    weight: 100