apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: serviceapp
    spec:
      containers:
      - command:
        - sleep
        - "9000"
        image: default-route-openshift-image-registry.apps.ocp.lab.cloudpak.site/labproj23/walletservice:1.0
        ports:
        - containerPort: 8081
        name: serviceapp
        resources: {}
        envFrom:
        - configMapRef:
            name: walletmap
status: {}