apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: deploy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: serviceapp
    spec:
      containers:
      - command:
        - sleep
        - "9000"
        image: image-registry.openshift-image-registry.svc:5000/default/busybox:latest
        ports:
        - containerPort: 8081
        name: serviceapp
        resources: {}
        envFrom:
        - configMapRef:
            name: walletmap
status: {}